# Site settings
title: Paul Upson
email: Paul.D.Upson@gmail.com
url: https://paulupson.uk
description: "An personal portfolio site for Paul Upson. Software Engineer and Architect. C#, ASP.NET, Node.js, javascript, HTML"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Paul Upson

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/fumblewit
  - title: facebook
    url: https://www.facebook.com/paul.upson
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: linkedin
    url: https://uk.linkedin.com/in/paul-upson-a8579814
  - title: github
    url: https://github.com/PaulUpson

# Build settings
markdown: kramdown
permalink: pretty
